name: Auth Service Deployment

on:
  workflow_run:
    workflows: ["Auth Service CI/CD"] # EXACT match to the name above
    types: [completed]

jobs:
  deploy-to-gcp:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: auth-service
          image: ghcr.io/${{ github.repository_owner }}/auth-service:latest
          region: us-central1
          flags: --allow-unauthenticated
          env_vars: |
            SPRING_PROFILES_ACTIVE=prod
            SPRING_DATASOURCE_URL=jdbc:postgresql:///auth_db?cloudSqlInstance=${{ secrets.GCP_INSTANCE_NAME }}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
            SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USER }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}
